import PostView from "@/containers/Blog/PostView";
import { groq } from "next-sanity";
import { client } from "@/pages/index.js";
import Head from "next/head";

const postsQuery = groq`*[_type == "posts"]`;

export const getStaticPaths = async () => {
  const posts = await client.fetch(postsQuery);

  const paths = posts?.map((item) => {
    return { params: { slug: item?._id } };
  });

  return { paths, fallback: false };
};

export const getStaticProps = async ({ params }) => {
  const queryParams = { slug: params?.slug ?? "" };
  const query = `*[_type == "posts" && _id == "${queryParams.slug}"][0]`;
  const post = await client.fetch(query);

  return { props: { post } };
};

const Index = ({ post }) => {
  return (
    <>
      <Head>
        <title>Blog - {post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <PostView post={post} />;
    </>
  );
};

Index.layout = true;
export default Index;
