import { Blog } from "@/containers/Blog";
import { groq } from "next-sanity";
import React from "react";
import { client } from "@/pages/index.js";
import Head from "next/head";

const postsQuery = groq`*[_type == "posts"]`;

export const getStaticProps = async () => {
  const posts = await client.fetch(postsQuery);

  return { props: { posts } };
};

const Index = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Blog posts={posts} />;
    </>
  );
};
Index.layout = true;
export default Index;
