import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import Homepage from "@/containers/Home";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Hind+Madurai&display=swap"
            rel="stylesheet"
          />
        </Head>
      </Head>
      <Homepage />
    </>
  );
}
