import Home from "@/containers/Home";
import Head from "next/head";
import { createClient } from "next-sanity";
import { useEffect, useState } from "react";

export const client = createClient({
  projectId: "hi7eel47",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false,
});

const Index = () => {
  // const posts = {
  //   user: [],
  //   blogs: [],
  // };

  // const [data, setData] = useState(posts);
  // useEffect(() => {
  //   client
  //     .fetch(`*[_type == "person"]`)
  //     .then((item) => {
  //       setData((prevstate) => {
  //         return {
  //           ...prevstate,
  //           user: item,
  //         };
  //       });
  //     })
  //     .catch((err) => {
  //       console.log("error", err);
  //     });

  //   client
  //     .fetch(`*[_type == "posts"]`)
  //     .then((item) => {
  //       setData((prevstate) => {
  //         return {
  //           ...prevstate,
  //           blogs: item,
  //         };
  //       });
  //     })
  //     .catch((err) => {
  //       console.log("error", err);
  //     });
  // }, []);
  // console.log("data", data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Hind+Madurai&display=swap"
            rel="stylesheet"
          />
        </Head>
      </Head>
      <Home />
    </>
  );
};
Index.layout = true;
export default Index;
