import React from "react";
import EnrollNow from "@/containers/EnrollNow";
import Head from "next/head";

const Index = () => {
  return (
    <>
      <Head>
        <title>Enroll for new Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <EnrollNow />
    </>
  );
};

Index.layout = true;
export default Index;
