import Privacy from "@/containers/Privacy";
import Head from "next/head";

const Index = () => {
  return (
    <>
      <Head>
        <title>Privacy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Privacy />
    </>
  );
};

Index.layout = true;
export default Index;
