import React from "react";
import Faq from "@/containers/Faq";
import Head from "next/head";

const Index = () => {
  return (
    <>
      <Head>
        <title>Frequently Asked Question - FAQ's</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Faq />
    </>
  );
};
Index.layout = true;
export default Index;
